# Generated by Django 5.2.8 on 2025-11-18 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Tarih')),
                ('total_visits', models.IntegerField(default=0, verbose_name='Toplam Ziyaret')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='Tekil Ziyaretçi')),
                ('avg_time_spent', models.IntegerField(default=0, verbose_name='Ortalama Süre (saniye)')),
            ],
            options={
                'verbose_name': 'Günlük İstatistik',
                'verbose_name_plural': 'Günlük İstatistikler',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=255, verbose_name='Sayfa URL')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ziyaret Tarihi')),
                ('session_id', models.CharField(max_length=100, verbose_name='Oturum ID')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Geçirilen Süre (saniye)')),
            ],
            options={
                'verbose_name': 'Sayfa Ziyareti',
                'verbose_name_plural': 'Sayfa Ziyaretleri',
                'ordering': ['-visit_date'],
            },
        ),
    ]
